name: Version Increase

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      versionToUpdate:
        description: 'Version to update'     
        required: true
        default: 'minor' 
        type: choice
        options:
        - major
        - minor
        - patch


jobs:
  version-ubuntu:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Get Version to env and increase it
      run: |
        output=$(python .github/workflows/get_version_and_update.py GViewCore/include/GView.hpp ${{ github.event.inputs.versionToUpdate }})
        echo "GVIEW_VERSION=$output" >> $GITHUB_ENV
    
    - name: Show Version
      run: echo "${{ env.GVIEW_VERSION }}"    

    - name: Commit files
      run: |
        git config --local user.email "zahariarauul+bot@gmail.com"
        git config --local user.name "rzaharia-bot"
        git commit -m "Updated GVIEW version ${{ secrets.GPG_BOT_KEY }}" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
